name: "Stale issue handler"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *" # This action would run every day at midnight

jobs: # Job to close stale PRs and issues. Documentation on the github action https://github.com/marketplace/actions/close-stale-issues
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label / comment or this will be closed in 5 days'
        stale-pr-message: 'This PR is stale because it has been open for 60 days with no activity. Remove stale label / comment or this will be closed in 5 days'
        days-before-stale: 60
        days-before-close: 5
        stale-pr-label: 'no-pr-activity'
        stale-issue-label: 'no-issue-activity'
        exempt-pr-labels: 'pending'
        exempt-issue-labels: 'pending'
